eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&userSSL=false
    username: root
    password: password
  jpa:
    show-sql: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/faxiu/config-repo
          username: faxiu
          password: hekai2pyy
          basedir: E:/study/sell/config/basedir
girl:
  name: yy
  age: 18
  
